spring:
  profiles:
    active:
      - dev

---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的间隔时间 （默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了五秒的间隔（默认是90秒）
    instance-id: dept-8001.com
    # prefer-ip-address: true
info:
   app.name: mldn-microcloud
   company.name: www.mldn.cn
   build.artifactId: $project.artifactId$
   build.version: $project.version$  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.mldn.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3308/mldn8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: '{cipher}AQAZFOS/FzAqFfFCNCHuv0QLzMjnm0z26N3ZSp/YafrTSJgomjQqgh79s4/OaO/DzdeE0qvv2vzXBBNd46xUKa6o7koEVa8A1DkI5S7LwxX2kwjpp/+25El1ydCJKMMBMGe3J2vbO0kJV64JQQ2+ZaMZdWcjHWlMGVmMNNBSGu/KZ1mgKynyIBmeMfaSSL+dgrzk7AEIGCMYcJkj9TSkAmN0E96bl00AXbxPi0nT+VUDrsu80U3B6zWDDWU5ulseZuJ+NAoqWQCCLmy9BZhFP5ii1dG7JGwdNl9NJ8zMkS+4UN41cJSTS3mctEiwPqjwQxkzGx+PD3SDB5wpr3VqQ5i+lUMWK82FTKvy2CIuDLr2xqORvnHnILgTF6h19YmQBDA='                              # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 1                                   # 数据库连接池的最小维持连接数    
      initial-size: 1                               # 初始化提供的连接数
      max-total: 1                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-provider-dept
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的间隔时间 （默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了五秒的间隔（默认是90秒）
    instance-id: dept-8001.com
    # prefer-ip-address: true
info:
   app.name: mldn-microcloud
   company.name: www.mldn.cn
   build.artifactId: $project.artifactId$
   build.version: $project.version$  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: cn.mldn.vo            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: beta
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3308/mldn8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: mldnjava                              # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 1                                   # 数据库连接池的最小维持连接数    
      initial-size: 1                               # 初始化提供的连接数
      max-total: 1                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-provider-dept

  
