spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  application:
    name: microcloud-config-eureka-client
server:
  port: 7001
security:
  basic:
    enabled: true
  user:
    name: edmindev
    password: mldnjava
eureka:
  client:
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-dev.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-7001.com
---
spring:
  profiles: beta
  application:
    name: microcloud-config-eureka-client
server:
  port: 7001
security:
  basic:
    enabled: true
  user:
    name: edminbeta
    password: mldnjava
eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-dev.com:7001/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-7001.com

  
